### ISSUE TITLE
How can you select rpi3 vs rpi1 toolchain?

### ISSUE THREAD

**Issue by richtong** [sdt/docker-raspberry-pi-cross-compiler#16]
Is this still the way to go, there seem to be lots of folks thinking about cross compilation these days.

I'm wondering how you are doing sys root and preinstalling packages as other have mentioned, but also how do you handle rpi3 specific binaries. That is arm7 or even arm8 compilation

**Comment by sdt** [comment]
I haven't touched this for a while now.

I originally had the toolchain selectable at runtime, but switched to hardcoding it, as the runtime selection made a lot of downstream things more difficult.

If multiple toolchains are preferable, it might be better to pass that in as a build arg when building the docker image.

Is there a toolchain [here](https://github.com/raspberrypi/tools/tree/master/arm-bcm2708) you'd rather use?  This one looks to have been added since I was last here: [arm-rpi-4.9.3-linux-gnueabihf](https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf)

**Comment by sdt** [comment]
@richtong please see https://github.com/sdt/docker-raspberry-pi-cross-compiler/issues/15#issuecomment-226926239 about sysroots

**Comment by sdt** [comment]
Closing as part of an old issue tidy-up. Please create a new issue if necessary.
