### ISSUE TITLE
Cross-compiling python

### ISSUE THREAD

**Issue by nedosa** [sdt/docker-raspberry-pi-cross-compiler#25]
I want to package a python app for arm - and cx_freeze it also, so that it becomes a self-contained executable - but failing miserably.

Is there a set of recommended steps on how to produce an arm binary for a python application ? 

Should I install python in the raspbian chroot environment or go about it in a different way ?

Thanks in advance for any help on this

**Comment by sdt** [comment]
Have you been able to get this to work on a raspberry pi?

I had a bit of a play with this using docker yesterday, and I think it's possible, but I wouldn't recommend it. You're making like a little hard for yourself.

This docker image contains a raspberry pi emulator, but that's really just included so that deb packages can be installed into the included raspbian sysroot. It's not really intended to be used as a raspberry pi emulator.

Something like this might be more what you need https://github.com/ryankurte/docker-rpi-emu

**Comment by nedosa** [comment]
I have the process working on the RPi, indeed. I'm trying to setup a build pipeline though and I don't want to rely on the RPi.

Thanks for your help on this, I think the `docker-rpi-emu` scripts might be a better fit than cross-compiling.

**Comment by sdt** [comment]
No worries @nedosa - hope it works out
