### ISSUE TITLE
Why do I get chpst: fatal: unable to run: cd: file does not exist ?

### ISSUE THREAD

**Issue by abhisheksoni27** [sdt/docker-raspberry-pi-cross-compiler#28]
`chpst: fatal: unable to run: cd: file does not exist`

**Comment by sdt** [comment]
I'll need a bit more information there @abhisheksoni27 

What command did you run to get that error?
What platform are you on?

**Comment by abhisheksoni27** [comment]
I followed the instructions listed in the readme. After that, I ran `wget <URL>` which failed with a similar.

Then, even though I don't know the directory structure inside the container, I tried running `cd random_dir`, which failed with that.

In the example bash files, after cloning, we cd into the repo, so maybe there's something I am missing.

OS: Ubuntu 17.04 64-bit

**Comment by sdt** [comment]
Ah, I see what's going on. Despite the similar messages, those commands are failing for different reasons.

`rpxc cd` fails because there is no `cd` program as such - `cd` is an internal bash command.

If you want to run `cd`, you'll need to do that _inside_ bash.

eg. `rpxc bash -c 'cd /dev && ls -alF'`

`rpxc wget` fails because the wget package is not installed in the docker image.

You can install it like this: `rpxc install-debian wget`

`rpxc wget` will work after that.

Note though that `rpxc` always bind mounts the current working directory on your host, so it might make more sense to do the `wget` locally, outside of docker.

What I recommend is to create a shell script that calls any build commands directly, and use `rpxc` to run that inside docker.

ie. `rpxc ./build.sh`
